/*
 * generated by Xtext 2.10.0
 */
package at.fhhagenberg.swml.xtext.solution.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SolutionAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("at/fhhagenberg/swml/xtext/solution/parser/antlr/internal/InternalSolution.tokens");
	}
}
