/*
 * generated by Xtext 2.10.0
 */
package at.fh.hagenberg.parser.antlr;

import at.fh.hagenberg.parser.antlr.internal.InternalSwmlParser;
import at.fh.hagenberg.services.SwmlGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class SwmlParser extends AbstractAntlrParser {

	@Inject
	private SwmlGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSwmlParser createParser(XtextTokenStream stream) {
		return new InternalSwmlParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "WebApplication";
	}

	public SwmlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SwmlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
