/*
 * generated by Xtext 2.10.0
 */
package at.fhhagenberg.swml.xtext.solution


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SolutionStandaloneSetup extends SolutionStandaloneSetupGenerated {

	def static void doSetup() {
		new SolutionStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
