/*
 * generated by Xtext 2.10.0
 */
package at.ooe.fh.mdm.herzog.dsl.proj


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ProjectGeneratorRuntimeModule extends AbstractProjectGeneratorRuntimeModule {
}
