/**
 * generated by Xtext 2.10.0
 */
package at.fh.hagenberg.validation;

import at.fh.hagenberg.validation.AbstractSwmlValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SwmlValidator extends AbstractSwmlValidator {
}
