/**
 * generated by Xtext 2.10.0
 */
package at.fh.hagenberg.swml.xtext.validation;

import at.fh.hagenberg.swml.xtext.language.Entity;
import at.fh.hagenberg.swml.xtext.language.LanguagePackage;
import at.fh.hagenberg.swml.xtext.validation.AbstractLanguageValidator;
import org.eclipse.xtext.validation.Check;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class LanguageValidator extends AbstractLanguageValidator {
  public final static String INVALID_NAME = "invalidName";
  
  /**
   * Validates the Entity name for starting with an capital letter.
   */
  @Check
  public void validateEntityNameStartsWithCapital(final Entity entity) {
    String _name = entity.getName();
    char _charAt = _name.charAt(0);
    boolean _isUpperCase = Character.isUpperCase(_charAt);
    boolean _not = (!_isUpperCase);
    if (_not) {
      this.warning("Name should start with a capital", LanguagePackage.Literals.ENTITY__NAME, LanguageValidator.INVALID_NAME);
    }
  }
}
