/**
 * generated by Xtext 2.10.0
 */
package at.fh.hagenberg.swml.xtext.language;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see at.fh.hagenberg.swml.xtext.language.LanguageFactory
 * @model kind="package"
 * @generated
 */
public interface LanguagePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "language";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.fh.at/hagenberg/swml/xtext/Language";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "language";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  LanguagePackage eINSTANCE = at.fh.hagenberg.swml.xtext.language.impl.LanguagePackageImpl.init();

  /**
   * The meta object id for the '{@link at.fh.hagenberg.swml.xtext.language.impl.WebApplicationImpl <em>Web Application</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see at.fh.hagenberg.swml.xtext.language.impl.WebApplicationImpl
   * @see at.fh.hagenberg.swml.xtext.language.impl.LanguagePackageImpl#getWebApplication()
   * @generated
   */
  int WEB_APPLICATION = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WEB_APPLICATION__NAME = 0;

  /**
   * The feature id for the '<em><b>Entities</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WEB_APPLICATION__ENTITIES = 1;

  /**
   * The feature id for the '<em><b>Relationships</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WEB_APPLICATION__RELATIONSHIPS = 2;

  /**
   * The number of structural features of the '<em>Web Application</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WEB_APPLICATION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link at.fh.hagenberg.swml.xtext.language.impl.RelationShipImpl <em>Relation Ship</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see at.fh.hagenberg.swml.xtext.language.impl.RelationShipImpl
   * @see at.fh.hagenberg.swml.xtext.language.impl.LanguagePackageImpl#getRelationShip()
   * @generated
   */
  int RELATION_SHIP = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_SHIP__NAME = 0;

  /**
   * The feature id for the '<em><b>Lower</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_SHIP__LOWER = 1;

  /**
   * The feature id for the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_SHIP__SOURCE = 2;

  /**
   * The feature id for the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_SHIP__TARGET = 3;

  /**
   * The feature id for the '<em><b>Opposite</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_SHIP__OPPOSITE = 4;

  /**
   * The number of structural features of the '<em>Relation Ship</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_SHIP_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link at.fh.hagenberg.swml.xtext.language.impl.EntityImpl <em>Entity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see at.fh.hagenberg.swml.xtext.language.impl.EntityImpl
   * @see at.fh.hagenberg.swml.xtext.language.impl.LanguagePackageImpl#getEntity()
   * @generated
   */
  int ENTITY = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__NAME = 0;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__ATTRIBUTES = 1;

  /**
   * The feature id for the '<em><b>Id</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__ID = 2;

  /**
   * The number of structural features of the '<em>Entity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link at.fh.hagenberg.swml.xtext.language.impl.AttributeImpl <em>Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see at.fh.hagenberg.swml.xtext.language.impl.AttributeImpl
   * @see at.fh.hagenberg.swml.xtext.language.impl.LanguagePackageImpl#getAttribute()
   * @generated
   */
  int ATTRIBUTE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__TYPE = 1;

  /**
   * The number of structural features of the '<em>Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link at.fh.hagenberg.swml.xtext.language.Datatype <em>Datatype</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see at.fh.hagenberg.swml.xtext.language.Datatype
   * @see at.fh.hagenberg.swml.xtext.language.impl.LanguagePackageImpl#getDatatype()
   * @generated
   */
  int DATATYPE = 4;


  /**
   * Returns the meta object for class '{@link at.fh.hagenberg.swml.xtext.language.WebApplication <em>Web Application</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Web Application</em>'.
   * @see at.fh.hagenberg.swml.xtext.language.WebApplication
   * @generated
   */
  EClass getWebApplication();

  /**
   * Returns the meta object for the attribute '{@link at.fh.hagenberg.swml.xtext.language.WebApplication#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see at.fh.hagenberg.swml.xtext.language.WebApplication#getName()
   * @see #getWebApplication()
   * @generated
   */
  EAttribute getWebApplication_Name();

  /**
   * Returns the meta object for the containment reference list '{@link at.fh.hagenberg.swml.xtext.language.WebApplication#getEntities <em>Entities</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entities</em>'.
   * @see at.fh.hagenberg.swml.xtext.language.WebApplication#getEntities()
   * @see #getWebApplication()
   * @generated
   */
  EReference getWebApplication_Entities();

  /**
   * Returns the meta object for the containment reference '{@link at.fh.hagenberg.swml.xtext.language.WebApplication#getRelationships <em>Relationships</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Relationships</em>'.
   * @see at.fh.hagenberg.swml.xtext.language.WebApplication#getRelationships()
   * @see #getWebApplication()
   * @generated
   */
  EReference getWebApplication_Relationships();

  /**
   * Returns the meta object for class '{@link at.fh.hagenberg.swml.xtext.language.RelationShip <em>Relation Ship</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Relation Ship</em>'.
   * @see at.fh.hagenberg.swml.xtext.language.RelationShip
   * @generated
   */
  EClass getRelationShip();

  /**
   * Returns the meta object for the attribute '{@link at.fh.hagenberg.swml.xtext.language.RelationShip#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see at.fh.hagenberg.swml.xtext.language.RelationShip#getName()
   * @see #getRelationShip()
   * @generated
   */
  EAttribute getRelationShip_Name();

  /**
   * Returns the meta object for the attribute '{@link at.fh.hagenberg.swml.xtext.language.RelationShip#getLower <em>Lower</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Lower</em>'.
   * @see at.fh.hagenberg.swml.xtext.language.RelationShip#getLower()
   * @see #getRelationShip()
   * @generated
   */
  EAttribute getRelationShip_Lower();

  /**
   * Returns the meta object for the reference '{@link at.fh.hagenberg.swml.xtext.language.RelationShip#getSource <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Source</em>'.
   * @see at.fh.hagenberg.swml.xtext.language.RelationShip#getSource()
   * @see #getRelationShip()
   * @generated
   */
  EReference getRelationShip_Source();

  /**
   * Returns the meta object for the reference '{@link at.fh.hagenberg.swml.xtext.language.RelationShip#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Target</em>'.
   * @see at.fh.hagenberg.swml.xtext.language.RelationShip#getTarget()
   * @see #getRelationShip()
   * @generated
   */
  EReference getRelationShip_Target();

  /**
   * Returns the meta object for the reference '{@link at.fh.hagenberg.swml.xtext.language.RelationShip#getOpposite <em>Opposite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Opposite</em>'.
   * @see at.fh.hagenberg.swml.xtext.language.RelationShip#getOpposite()
   * @see #getRelationShip()
   * @generated
   */
  EReference getRelationShip_Opposite();

  /**
   * Returns the meta object for class '{@link at.fh.hagenberg.swml.xtext.language.Entity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entity</em>'.
   * @see at.fh.hagenberg.swml.xtext.language.Entity
   * @generated
   */
  EClass getEntity();

  /**
   * Returns the meta object for the attribute '{@link at.fh.hagenberg.swml.xtext.language.Entity#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see at.fh.hagenberg.swml.xtext.language.Entity#getName()
   * @see #getEntity()
   * @generated
   */
  EAttribute getEntity_Name();

  /**
   * Returns the meta object for the containment reference list '{@link at.fh.hagenberg.swml.xtext.language.Entity#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attributes</em>'.
   * @see at.fh.hagenberg.swml.xtext.language.Entity#getAttributes()
   * @see #getEntity()
   * @generated
   */
  EReference getEntity_Attributes();

  /**
   * Returns the meta object for the reference '{@link at.fh.hagenberg.swml.xtext.language.Entity#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Id</em>'.
   * @see at.fh.hagenberg.swml.xtext.language.Entity#getId()
   * @see #getEntity()
   * @generated
   */
  EReference getEntity_Id();

  /**
   * Returns the meta object for class '{@link at.fh.hagenberg.swml.xtext.language.Attribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute</em>'.
   * @see at.fh.hagenberg.swml.xtext.language.Attribute
   * @generated
   */
  EClass getAttribute();

  /**
   * Returns the meta object for the attribute '{@link at.fh.hagenberg.swml.xtext.language.Attribute#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see at.fh.hagenberg.swml.xtext.language.Attribute#getName()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Name();

  /**
   * Returns the meta object for the attribute '{@link at.fh.hagenberg.swml.xtext.language.Attribute#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see at.fh.hagenberg.swml.xtext.language.Attribute#getType()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Type();

  /**
   * Returns the meta object for enum '{@link at.fh.hagenberg.swml.xtext.language.Datatype <em>Datatype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Datatype</em>'.
   * @see at.fh.hagenberg.swml.xtext.language.Datatype
   * @generated
   */
  EEnum getDatatype();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  LanguageFactory getLanguageFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link at.fh.hagenberg.swml.xtext.language.impl.WebApplicationImpl <em>Web Application</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see at.fh.hagenberg.swml.xtext.language.impl.WebApplicationImpl
     * @see at.fh.hagenberg.swml.xtext.language.impl.LanguagePackageImpl#getWebApplication()
     * @generated
     */
    EClass WEB_APPLICATION = eINSTANCE.getWebApplication();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WEB_APPLICATION__NAME = eINSTANCE.getWebApplication_Name();

    /**
     * The meta object literal for the '<em><b>Entities</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WEB_APPLICATION__ENTITIES = eINSTANCE.getWebApplication_Entities();

    /**
     * The meta object literal for the '<em><b>Relationships</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WEB_APPLICATION__RELATIONSHIPS = eINSTANCE.getWebApplication_Relationships();

    /**
     * The meta object literal for the '{@link at.fh.hagenberg.swml.xtext.language.impl.RelationShipImpl <em>Relation Ship</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see at.fh.hagenberg.swml.xtext.language.impl.RelationShipImpl
     * @see at.fh.hagenberg.swml.xtext.language.impl.LanguagePackageImpl#getRelationShip()
     * @generated
     */
    EClass RELATION_SHIP = eINSTANCE.getRelationShip();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RELATION_SHIP__NAME = eINSTANCE.getRelationShip_Name();

    /**
     * The meta object literal for the '<em><b>Lower</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RELATION_SHIP__LOWER = eINSTANCE.getRelationShip_Lower();

    /**
     * The meta object literal for the '<em><b>Source</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATION_SHIP__SOURCE = eINSTANCE.getRelationShip_Source();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATION_SHIP__TARGET = eINSTANCE.getRelationShip_Target();

    /**
     * The meta object literal for the '<em><b>Opposite</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATION_SHIP__OPPOSITE = eINSTANCE.getRelationShip_Opposite();

    /**
     * The meta object literal for the '{@link at.fh.hagenberg.swml.xtext.language.impl.EntityImpl <em>Entity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see at.fh.hagenberg.swml.xtext.language.impl.EntityImpl
     * @see at.fh.hagenberg.swml.xtext.language.impl.LanguagePackageImpl#getEntity()
     * @generated
     */
    EClass ENTITY = eINSTANCE.getEntity();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTITY__NAME = eINSTANCE.getEntity_Name();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY__ATTRIBUTES = eINSTANCE.getEntity_Attributes();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY__ID = eINSTANCE.getEntity_Id();

    /**
     * The meta object literal for the '{@link at.fh.hagenberg.swml.xtext.language.impl.AttributeImpl <em>Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see at.fh.hagenberg.swml.xtext.language.impl.AttributeImpl
     * @see at.fh.hagenberg.swml.xtext.language.impl.LanguagePackageImpl#getAttribute()
     * @generated
     */
    EClass ATTRIBUTE = eINSTANCE.getAttribute();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__NAME = eINSTANCE.getAttribute_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__TYPE = eINSTANCE.getAttribute_Type();

    /**
     * The meta object literal for the '{@link at.fh.hagenberg.swml.xtext.language.Datatype <em>Datatype</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see at.fh.hagenberg.swml.xtext.language.Datatype
     * @see at.fh.hagenberg.swml.xtext.language.impl.LanguagePackageImpl#getDatatype()
     * @generated
     */
    EEnum DATATYPE = eINSTANCE.getDatatype();

  }

} //LanguagePackage
