/*
 * generated by Xtext 2.9.2
 */
package at.ooe.fh.mdm.herzog.dsl.proj


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ProjectGeneratorStandaloneSetup extends ProjectGeneratorStandaloneSetupGenerated {

	def static void doSetup() {
		new ProjectGeneratorStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
