/*
 * generated by Xtext 2.10.0
 */
package at.ooe.fh.mdm.herzog.dsl.proj.ui;

import at.ooe.fh.mdm.herzog.dsl.proj.ProjectGenerator.ui.internal.ProjectGeneratorActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ProjectGeneratorExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ProjectGeneratorActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ProjectGeneratorActivator.getInstance().getInjector(ProjectGeneratorActivator.AT_OOE_FH_MDM_HERZOG_DSL_PROJ_PROJECTGENERATOR);
	}
	
}
