/*
 * generated by Xtext 2.10.0
 */
package at.fh.hagenberg.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractSwmlValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(at.fh.hagenberg.swml.SwmlPackage.eINSTANCE);
		return result;
	}
	
}
