/*
 * generated by Xtext 2.9.2
 */
package at.ooe.fh.mdm.herzog.dsl.proj.idea.lang;

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public final class ProjectGeneratorLanguage extends AbstractXtextLanguage {

	public static final ProjectGeneratorLanguage INSTANCE = new ProjectGeneratorLanguage();

	private ProjectGeneratorLanguage() {
		super("at.ooe.fh.mdm.herzog.dsl.proj.ProjectGenerator");
	}

}
