/**
 * generated by Xtext 2.9.2
 */
package at.ooe.fh.mdm.herzog.dsl.proj.scoping;

import at.ooe.fh.mdm.herzog.dsl.proj.scoping.AbstractProjectGeneratorScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class ProjectGeneratorScopeProvider extends AbstractProjectGeneratorScopeProvider {
}
