/*
 * generated by Xtext 2.10.0
 */
package at.fhhagenberg.swml.xtext.solution.ide.contentassist.antlr;

import at.fhhagenberg.swml.xtext.solution.ide.contentassist.antlr.internal.InternalSolutionParser;
import at.fhhagenberg.swml.xtext.solution.services.SolutionGrammarAccess;
import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

public class SolutionParser extends AbstractContentAssistParser {

	@Inject
	private SolutionGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalSolutionParser createParser() {
		InternalSolutionParser result = new InternalSolutionParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getWebPageAccess().getAlternatives(), "rule__WebPage__Alternatives");
					put(grammarAccess.getDynamicPageAccess().getAlternatives(), "rule__DynamicPage__Alternatives");
					put(grammarAccess.getEditablePageAccess().getAlternatives(), "rule__EditablePage__Alternatives");
					put(grammarAccess.getRoleNumberAccess().getAlternatives(), "rule__RoleNumber__Alternatives");
					put(grammarAccess.getLinkAccess().getAlternatives(), "rule__Link__Alternatives");
					put(grammarAccess.getDatatypeAccess().getAlternatives(), "rule__Datatype__Alternatives");
					put(grammarAccess.getWebApplicationAccess().getGroup(), "rule__WebApplication__Group__0");
					put(grammarAccess.getStaticPageAccess().getGroup(), "rule__StaticPage__Group__0");
					put(grammarAccess.getEntityPageAccess().getGroup(), "rule__EntityPage__Group__0");
					put(grammarAccess.getEntityPageAccess().getGroup_6(), "rule__EntityPage__Group_6__0");
					put(grammarAccess.getCreatePageAccess().getGroup(), "rule__CreatePage__Group__0");
					put(grammarAccess.getCreatePageAccess().getGroup_8(), "rule__CreatePage__Group_8__0");
					put(grammarAccess.getUpdatePageAccess().getGroup(), "rule__UpdatePage__Group__0");
					put(grammarAccess.getUpdatePageAccess().getGroup_8(), "rule__UpdatePage__Group_8__0");
					put(grammarAccess.getDeletePageAccess().getGroup(), "rule__DeletePage__Group__0");
					put(grammarAccess.getDeletePageAccess().getGroup_8(), "rule__DeletePage__Group_8__0");
					put(grammarAccess.getIndexPageAccess().getGroup(), "rule__IndexPage__Group__0");
					put(grammarAccess.getIndexPageAccess().getGroup_8(), "rule__IndexPage__Group_8__0");
					put(grammarAccess.getEntityAccess().getGroup(), "rule__Entity__Group__0");
					put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
					put(grammarAccess.getRelationshipAccess().getGroup(), "rule__Relationship__Group__0");
					put(grammarAccess.getRelationshipAccess().getGroup_15(), "rule__Relationship__Group_15__0");
					put(grammarAccess.getNonContextualLinkAccess().getGroup(), "rule__NonContextualLink__Group__0");
					put(grammarAccess.getContextualLinkAccess().getGroup(), "rule__ContextualLink__Group__0");
					put(grammarAccess.getWebApplicationAccess().getNameAssignment_1(), "rule__WebApplication__NameAssignment_1");
					put(grammarAccess.getWebApplicationAccess().getEntitiesAssignment_3(), "rule__WebApplication__EntitiesAssignment_3");
					put(grammarAccess.getWebApplicationAccess().getRelationshipsAssignment_4(), "rule__WebApplication__RelationshipsAssignment_4");
					put(grammarAccess.getWebApplicationAccess().getWebPagesAssignment_5(), "rule__WebApplication__WebPagesAssignment_5");
					put(grammarAccess.getWebApplicationAccess().getHomepageAssignment_7(), "rule__WebApplication__HomepageAssignment_7");
					put(grammarAccess.getWebApplicationAccess().getCreationDateAssignment_10(), "rule__WebApplication__CreationDateAssignment_10");
					put(grammarAccess.getStaticPageAccess().getNameAssignment_1(), "rule__StaticPage__NameAssignment_1");
					put(grammarAccess.getStaticPageAccess().getRelativeURLAssignment_4(), "rule__StaticPage__RelativeURLAssignment_4");
					put(grammarAccess.getStaticPageAccess().getSourceAssignment_5(), "rule__StaticPage__SourceAssignment_5");
					put(grammarAccess.getStaticPageAccess().getHomeAssignment_7(), "rule__StaticPage__HomeAssignment_7");
					put(grammarAccess.getEntityPageAccess().getNameAssignment_1(), "rule__EntityPage__NameAssignment_1");
					put(grammarAccess.getEntityPageAccess().getSourceAssignment_3(), "rule__EntityPage__SourceAssignment_3");
					put(grammarAccess.getEntityPageAccess().getHomeAssignment_5(), "rule__EntityPage__HomeAssignment_5");
					put(grammarAccess.getEntityPageAccess().getWebPagesAssignment_6_1(), "rule__EntityPage__WebPagesAssignment_6_1");
					put(grammarAccess.getEntityPageAccess().getEntityAssignment_8(), "rule__EntityPage__EntityAssignment_8");
					put(grammarAccess.getCreatePageAccess().getNameAssignment_1(), "rule__CreatePage__NameAssignment_1");
					put(grammarAccess.getCreatePageAccess().getSourceAssignment_3(), "rule__CreatePage__SourceAssignment_3");
					put(grammarAccess.getCreatePageAccess().getHomeAssignment_5(), "rule__CreatePage__HomeAssignment_5");
					put(grammarAccess.getCreatePageAccess().getEntityAssignment_7(), "rule__CreatePage__EntityAssignment_7");
					put(grammarAccess.getCreatePageAccess().getWebPagesAssignment_8_1(), "rule__CreatePage__WebPagesAssignment_8_1");
					put(grammarAccess.getCreatePageAccess().getBackAssignment_10(), "rule__CreatePage__BackAssignment_10");
					put(grammarAccess.getUpdatePageAccess().getNameAssignment_1(), "rule__UpdatePage__NameAssignment_1");
					put(grammarAccess.getUpdatePageAccess().getSourceAssignment_3(), "rule__UpdatePage__SourceAssignment_3");
					put(grammarAccess.getUpdatePageAccess().getHomeAssignment_5(), "rule__UpdatePage__HomeAssignment_5");
					put(grammarAccess.getUpdatePageAccess().getEntityAssignment_7(), "rule__UpdatePage__EntityAssignment_7");
					put(grammarAccess.getUpdatePageAccess().getWebPagesAssignment_8_1(), "rule__UpdatePage__WebPagesAssignment_8_1");
					put(grammarAccess.getUpdatePageAccess().getBackAssignment_10(), "rule__UpdatePage__BackAssignment_10");
					put(grammarAccess.getDeletePageAccess().getNameAssignment_1(), "rule__DeletePage__NameAssignment_1");
					put(grammarAccess.getDeletePageAccess().getSourceAssignment_3(), "rule__DeletePage__SourceAssignment_3");
					put(grammarAccess.getDeletePageAccess().getHomeAssignment_5(), "rule__DeletePage__HomeAssignment_5");
					put(grammarAccess.getDeletePageAccess().getEntityAssignment_7(), "rule__DeletePage__EntityAssignment_7");
					put(grammarAccess.getDeletePageAccess().getWebPagesAssignment_8_1(), "rule__DeletePage__WebPagesAssignment_8_1");
					put(grammarAccess.getDeletePageAccess().getBackAssignment_10(), "rule__DeletePage__BackAssignment_10");
					put(grammarAccess.getIndexPageAccess().getNameAssignment_1(), "rule__IndexPage__NameAssignment_1");
					put(grammarAccess.getIndexPageAccess().getSourceAssignment_3(), "rule__IndexPage__SourceAssignment_3");
					put(grammarAccess.getIndexPageAccess().getHomeAssignment_5(), "rule__IndexPage__HomeAssignment_5");
					put(grammarAccess.getIndexPageAccess().getEntityAssignment_7(), "rule__IndexPage__EntityAssignment_7");
					put(grammarAccess.getIndexPageAccess().getWebPagesAssignment_8_1(), "rule__IndexPage__WebPagesAssignment_8_1");
					put(grammarAccess.getIndexPageAccess().getBackAssignment_10(), "rule__IndexPage__BackAssignment_10");
					put(grammarAccess.getEntityAccess().getNameAssignment_1(), "rule__Entity__NameAssignment_1");
					put(grammarAccess.getEntityAccess().getAttributesAssignment_3(), "rule__Entity__AttributesAssignment_3");
					put(grammarAccess.getEntityAccess().getIdAssignment_5(), "rule__Entity__IdAssignment_5");
					put(grammarAccess.getAttributeAccess().getNameAssignment_1(), "rule__Attribute__NameAssignment_1");
					put(grammarAccess.getAttributeAccess().getTypeAssignment_3(), "rule__Attribute__TypeAssignment_3");
					put(grammarAccess.getRelationshipAccess().getNameAssignment_1(), "rule__Relationship__NameAssignment_1");
					put(grammarAccess.getRelationshipAccess().getLowerAssignment_4(), "rule__Relationship__LowerAssignment_4");
					put(grammarAccess.getRelationshipAccess().getUpperAssignment_7(), "rule__Relationship__UpperAssignment_7");
					put(grammarAccess.getRelationshipAccess().getSourceAssignment_10(), "rule__Relationship__SourceAssignment_10");
					put(grammarAccess.getRelationshipAccess().getTargetAssignment_13(), "rule__Relationship__TargetAssignment_13");
					put(grammarAccess.getRelationshipAccess().getRefAssignment_15_1(), "rule__Relationship__RefAssignment_15_1");
					put(grammarAccess.getNonContextualLinkAccess().getNameAssignment_1(), "rule__NonContextualLink__NameAssignment_1");
					put(grammarAccess.getNonContextualLinkAccess().getTargetAssignment_3(), "rule__NonContextualLink__TargetAssignment_3");
					put(grammarAccess.getContextualLinkAccess().getNameAssignment_1(), "rule__ContextualLink__NameAssignment_1");
					put(grammarAccess.getContextualLinkAccess().getTargetAssignment_3(), "rule__ContextualLink__TargetAssignment_3");
					put(grammarAccess.getContextualLinkAccess().getInformationAssignment_5(), "rule__ContextualLink__InformationAssignment_5");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalSolutionParser typedParser = (InternalSolutionParser) parser;
			typedParser.entryRuleWebApplication();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public SolutionGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SolutionGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
