/*
 * generated by Xtext 2.10.0
 */
package at.fhhagenberg.swml.xtext.solution.serializer;

import at.fhhagenberg.swml.xtext.solution.services.SolutionGrammarAccess;
import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class SolutionSyntacticSequencer extends AbstractSyntacticSequencer {

	protected SolutionGrammarAccess grammarAccess;
	protected AbstractElementAlias match_CreatePage_InnerPagesKeyword_8_0_q;
	protected AbstractElementAlias match_DeletePage_InnerPagesKeyword_8_0_q;
	protected AbstractElementAlias match_EntityPage_InnerPagesKeyword_6_0_q;
	protected AbstractElementAlias match_IndexPage_InnerPagesKeyword_8_0_q;
	protected AbstractElementAlias match_UpdatePage_InnerPagesKeyword_8_0_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (SolutionGrammarAccess) access;
		match_CreatePage_InnerPagesKeyword_8_0_q = new TokenAlias(false, true, grammarAccess.getCreatePageAccess().getInnerPagesKeyword_8_0());
		match_DeletePage_InnerPagesKeyword_8_0_q = new TokenAlias(false, true, grammarAccess.getDeletePageAccess().getInnerPagesKeyword_8_0());
		match_EntityPage_InnerPagesKeyword_6_0_q = new TokenAlias(false, true, grammarAccess.getEntityPageAccess().getInnerPagesKeyword_6_0());
		match_IndexPage_InnerPagesKeyword_8_0_q = new TokenAlias(false, true, grammarAccess.getIndexPageAccess().getInnerPagesKeyword_8_0());
		match_UpdatePage_InnerPagesKeyword_8_0_q = new TokenAlias(false, true, grammarAccess.getUpdatePageAccess().getInnerPagesKeyword_8_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_CreatePage_InnerPagesKeyword_8_0_q.equals(syntax))
				emit_CreatePage_InnerPagesKeyword_8_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_DeletePage_InnerPagesKeyword_8_0_q.equals(syntax))
				emit_DeletePage_InnerPagesKeyword_8_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_EntityPage_InnerPagesKeyword_6_0_q.equals(syntax))
				emit_EntityPage_InnerPagesKeyword_6_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_IndexPage_InnerPagesKeyword_8_0_q.equals(syntax))
				emit_IndexPage_InnerPagesKeyword_8_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_UpdatePage_InnerPagesKeyword_8_0_q.equals(syntax))
				emit_UpdatePage_InnerPagesKeyword_8_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     'innerPages'?
	 *
	 * This ambiguous syntax occurs at:
	 *     entity=[Entity|ID] (ambiguity) 'back' back=ContextualLink
	 */
	protected void emit_CreatePage_InnerPagesKeyword_8_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'innerPages'?
	 *
	 * This ambiguous syntax occurs at:
	 *     entity=[Entity|ID] (ambiguity) 'back' back=ContextualLink
	 */
	protected void emit_DeletePage_InnerPagesKeyword_8_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'innerPages'?
	 *
	 * This ambiguous syntax occurs at:
	 *     home=[NonContextualLink|ID] (ambiguity) 'entity' entity=[Entity|ID]
	 */
	protected void emit_EntityPage_InnerPagesKeyword_6_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'innerPages'?
	 *
	 * This ambiguous syntax occurs at:
	 *     entity=[Entity|ID] (ambiguity) 'back' back=ContextualLink
	 */
	protected void emit_IndexPage_InnerPagesKeyword_8_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'innerPages'?
	 *
	 * This ambiguous syntax occurs at:
	 *     entity=[Entity|ID] (ambiguity) 'back' back=ContextualLink
	 */
	protected void emit_UpdatePage_InnerPagesKeyword_8_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
