/*
 * generated by Xtext 2.9.2
 */
package at.ooe.fh.mdm.herzog.dsl.proj.idea.highlighting;

import at.ooe.fh.mdm.herzog.dsl.proj.idea.lang.ProjectGeneratorLanguage;
import org.eclipse.xtext.idea.highlighting.SemanticHighlightVisitor;

public class ProjectGeneratorSemanticHighlightVisitor extends SemanticHighlightVisitor {
	public ProjectGeneratorSemanticHighlightVisitor() {
		ProjectGeneratorLanguage.INSTANCE.injectMembers(this);
	}
}
