/*
 * generated by Xtext 2.9.2
 */
package at.ooe.fh.mdm.herzog.dsl.proj.idea.highlighting;

import at.ooe.fh.mdm.herzog.dsl.proj.idea.lang.ProjectGeneratorLanguage;
import com.intellij.openapi.fileTypes.SingleLazyInstanceSyntaxHighlighterFactory;
import com.intellij.openapi.fileTypes.SyntaxHighlighter;
import org.jetbrains.annotations.NotNull;

public class ProjectGeneratorSyntaxHighlighterFactory extends SingleLazyInstanceSyntaxHighlighterFactory {
	
	@Override
    @NotNull
    protected SyntaxHighlighter createHighlighter() {
        return ProjectGeneratorLanguage.INSTANCE.getInstance(SyntaxHighlighter.class);
    }
}
