/**
 * generated by Xtext 2.10.0
 */
package at.fhhagenberg.swml.xtext.solution;

import at.fhhagenberg.MyConverterService;
import at.fhhagenberg.swml.xtext.solution.AbstractSolutionRuntimeModule;
import org.eclipse.xtext.conversion.IValueConverterService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SolutionRuntimeModule extends AbstractSolutionRuntimeModule {
  @Override
  public Class<? extends IValueConverterService> bindIValueConverterService() {
    return MyConverterService.class;
  }
}
