/*
 * generated by Xtext 2.9.2
 */
package at.ooe.fh.mdm.herzog.dsl.proj.idea.lang.psi;

import at.ooe.fh.mdm.herzog.dsl.proj.idea.lang.ProjectGeneratorLanguage;
import com.intellij.psi.util.PsiModificationTracker;
import org.eclipse.xtext.psi.BaseXtextCodeBlockModificationListener;

public class ProjectGeneratorCodeBlockModificationListener extends BaseXtextCodeBlockModificationListener {

	public ProjectGeneratorCodeBlockModificationListener(PsiModificationTracker psiModificationTracker) {
		super(ProjectGeneratorLanguage.INSTANCE, psiModificationTracker);
	}

}
