/**
 * generated by Xtext 2.10.0
 */
package at.fh.hagenberg.swml.xtext;

import at.fh.hagenberg.swml.xtext.LanguageStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class LanguageStandaloneSetup extends LanguageStandaloneSetupGenerated {
  public static void doSetup() {
    LanguageStandaloneSetup _languageStandaloneSetup = new LanguageStandaloneSetup();
    _languageStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
