/**
 * generated by Xtext 2.10.0
 */
package at.fhhagenberg.swml.xtext.solution.solution;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link at.fhhagenberg.swml.xtext.solution.solution.Attribute#getName <em>Name</em>}</li>
 *   <li>{@link at.fhhagenberg.swml.xtext.solution.solution.Attribute#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see at.fhhagenberg.swml.xtext.solution.solution.SolutionPackage#getAttribute()
 * @model
 * @generated
 */
public interface Attribute extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see at.fhhagenberg.swml.xtext.solution.solution.SolutionPackage#getAttribute_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link at.fhhagenberg.swml.xtext.solution.solution.Attribute#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link at.fhhagenberg.swml.xtext.solution.solution.Datatype}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see at.fhhagenberg.swml.xtext.solution.solution.Datatype
   * @see #setType(Datatype)
   * @see at.fhhagenberg.swml.xtext.solution.solution.SolutionPackage#getAttribute_Type()
   * @model
   * @generated
   */
  Datatype getType();

  /**
   * Sets the value of the '{@link at.fhhagenberg.swml.xtext.solution.solution.Attribute#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see at.fhhagenberg.swml.xtext.solution.solution.Datatype
   * @see #getType()
   * @generated
   */
  void setType(Datatype value);

} // Attribute
