/**
 * generated by Xtext 2.10.0
 */
package at.fhhagenberg.swml.xtext.solution.solution;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entity Page</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see at.fhhagenberg.swml.xtext.solution.solution.SolutionPackage#getEntityPage()
 * @model
 * @generated
 */
public interface EntityPage extends DynamicPage
{
} // EntityPage
