/**
 * generated by Xtext 2.10.0
 */
package at.fhhagenberg.swml.xtext.solution.solution;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Non Contextual Link</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see at.fhhagenberg.swml.xtext.solution.solution.SolutionPackage#getNonContextualLink()
 * @model
 * @generated
 */
public interface NonContextualLink extends Link
{
} // NonContextualLink
