/**
 * generated by Xtext 2.10.0
 */
package at.fhhagenberg.swml.xtext.solution.solution;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Relationship</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link at.fhhagenberg.swml.xtext.solution.solution.Relationship#getName <em>Name</em>}</li>
 *   <li>{@link at.fhhagenberg.swml.xtext.solution.solution.Relationship#getLower <em>Lower</em>}</li>
 *   <li>{@link at.fhhagenberg.swml.xtext.solution.solution.Relationship#getUpper <em>Upper</em>}</li>
 *   <li>{@link at.fhhagenberg.swml.xtext.solution.solution.Relationship#getSource <em>Source</em>}</li>
 *   <li>{@link at.fhhagenberg.swml.xtext.solution.solution.Relationship#getTarget <em>Target</em>}</li>
 *   <li>{@link at.fhhagenberg.swml.xtext.solution.solution.Relationship#getRef <em>Ref</em>}</li>
 * </ul>
 *
 * @see at.fhhagenberg.swml.xtext.solution.solution.SolutionPackage#getRelationship()
 * @model
 * @generated
 */
public interface Relationship extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see at.fhhagenberg.swml.xtext.solution.solution.SolutionPackage#getRelationship_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link at.fhhagenberg.swml.xtext.solution.solution.Relationship#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Lower</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Lower</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lower</em>' attribute.
   * @see #setLower(Integer)
   * @see at.fhhagenberg.swml.xtext.solution.solution.SolutionPackage#getRelationship_Lower()
   * @model
   * @generated
   */
  Integer getLower();

  /**
   * Sets the value of the '{@link at.fhhagenberg.swml.xtext.solution.solution.Relationship#getLower <em>Lower</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lower</em>' attribute.
   * @see #getLower()
   * @generated
   */
  void setLower(Integer value);

  /**
   * Returns the value of the '<em><b>Upper</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Upper</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Upper</em>' attribute.
   * @see #setUpper(Integer)
   * @see at.fhhagenberg.swml.xtext.solution.solution.SolutionPackage#getRelationship_Upper()
   * @model
   * @generated
   */
  Integer getUpper();

  /**
   * Sets the value of the '{@link at.fhhagenberg.swml.xtext.solution.solution.Relationship#getUpper <em>Upper</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Upper</em>' attribute.
   * @see #getUpper()
   * @generated
   */
  void setUpper(Integer value);

  /**
   * Returns the value of the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Source</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' reference.
   * @see #setSource(Entity)
   * @see at.fhhagenberg.swml.xtext.solution.solution.SolutionPackage#getRelationship_Source()
   * @model
   * @generated
   */
  Entity getSource();

  /**
   * Sets the value of the '{@link at.fhhagenberg.swml.xtext.solution.solution.Relationship#getSource <em>Source</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' reference.
   * @see #getSource()
   * @generated
   */
  void setSource(Entity value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Target</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' reference.
   * @see #setTarget(Entity)
   * @see at.fhhagenberg.swml.xtext.solution.solution.SolutionPackage#getRelationship_Target()
   * @model
   * @generated
   */
  Entity getTarget();

  /**
   * Sets the value of the '{@link at.fhhagenberg.swml.xtext.solution.solution.Relationship#getTarget <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(Entity value);

  /**
   * Returns the value of the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ref</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' reference.
   * @see #setRef(Relationship)
   * @see at.fhhagenberg.swml.xtext.solution.solution.SolutionPackage#getRelationship_Ref()
   * @model
   * @generated
   */
  Relationship getRef();

  /**
   * Sets the value of the '{@link at.fhhagenberg.swml.xtext.solution.solution.Relationship#getRef <em>Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' reference.
   * @see #getRef()
   * @generated
   */
  void setRef(Relationship value);

} // Relationship
