/**
 * generated by Xtext 2.10.0
 */
package at.fhhagenberg.swml.xtext.solution.solution;

import java.util.Date;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Web Application</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link at.fhhagenberg.swml.xtext.solution.solution.WebApplication#getName <em>Name</em>}</li>
 *   <li>{@link at.fhhagenberg.swml.xtext.solution.solution.WebApplication#getEntities <em>Entities</em>}</li>
 *   <li>{@link at.fhhagenberg.swml.xtext.solution.solution.WebApplication#getRelationships <em>Relationships</em>}</li>
 *   <li>{@link at.fhhagenberg.swml.xtext.solution.solution.WebApplication#getWebPages <em>Web Pages</em>}</li>
 *   <li>{@link at.fhhagenberg.swml.xtext.solution.solution.WebApplication#getHomepage <em>Homepage</em>}</li>
 *   <li>{@link at.fhhagenberg.swml.xtext.solution.solution.WebApplication#getCreationDate <em>Creation Date</em>}</li>
 * </ul>
 *
 * @see at.fhhagenberg.swml.xtext.solution.solution.SolutionPackage#getWebApplication()
 * @model
 * @generated
 */
public interface WebApplication extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see at.fhhagenberg.swml.xtext.solution.solution.SolutionPackage#getWebApplication_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link at.fhhagenberg.swml.xtext.solution.solution.WebApplication#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Entities</b></em>' containment reference list.
   * The list contents are of type {@link at.fhhagenberg.swml.xtext.solution.solution.Entity}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Entities</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entities</em>' containment reference list.
   * @see at.fhhagenberg.swml.xtext.solution.solution.SolutionPackage#getWebApplication_Entities()
   * @model containment="true"
   * @generated
   */
  EList<Entity> getEntities();

  /**
   * Returns the value of the '<em><b>Relationships</b></em>' containment reference list.
   * The list contents are of type {@link at.fhhagenberg.swml.xtext.solution.solution.Relationship}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Relationships</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relationships</em>' containment reference list.
   * @see at.fhhagenberg.swml.xtext.solution.solution.SolutionPackage#getWebApplication_Relationships()
   * @model containment="true"
   * @generated
   */
  EList<Relationship> getRelationships();

  /**
   * Returns the value of the '<em><b>Web Pages</b></em>' containment reference list.
   * The list contents are of type {@link at.fhhagenberg.swml.xtext.solution.solution.WebPage}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Web Pages</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Web Pages</em>' containment reference list.
   * @see at.fhhagenberg.swml.xtext.solution.solution.SolutionPackage#getWebApplication_WebPages()
   * @model containment="true"
   * @generated
   */
  EList<WebPage> getWebPages();

  /**
   * Returns the value of the '<em><b>Homepage</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Homepage</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Homepage</em>' reference.
   * @see #setHomepage(StaticPage)
   * @see at.fhhagenberg.swml.xtext.solution.solution.SolutionPackage#getWebApplication_Homepage()
   * @model
   * @generated
   */
  StaticPage getHomepage();

  /**
   * Sets the value of the '{@link at.fhhagenberg.swml.xtext.solution.solution.WebApplication#getHomepage <em>Homepage</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Homepage</em>' reference.
   * @see #getHomepage()
   * @generated
   */
  void setHomepage(StaticPage value);

  /**
   * Returns the value of the '<em><b>Creation Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Creation Date</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Creation Date</em>' attribute.
   * @see #setCreationDate(Date)
   * @see at.fhhagenberg.swml.xtext.solution.solution.SolutionPackage#getWebApplication_CreationDate()
   * @model
   * @generated
   */
  Date getCreationDate();

  /**
   * Sets the value of the '{@link at.fhhagenberg.swml.xtext.solution.solution.WebApplication#getCreationDate <em>Creation Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Creation Date</em>' attribute.
   * @see #getCreationDate()
   * @generated
   */
  void setCreationDate(Date value);

} // WebApplication
