/*
 * generated by Xtext 2.9.2
 */
package at.ooe.fh.mdm.herzog.dsl.proj.idea.lang.pom;

import at.ooe.fh.mdm.herzog.dsl.proj.idea.lang.ProjectGeneratorLanguage;
import org.eclipse.xtext.idea.pom.AbstractXtextPomDeclarationSearcher;

public class ProjectGeneratorPomDeclarationSearcher extends AbstractXtextPomDeclarationSearcher {

	public ProjectGeneratorPomDeclarationSearcher() {
		super(ProjectGeneratorLanguage.INSTANCE);
	}
}
