/*
 * generated by Xtext 2.10.0
 */
package at.fh.hagenberg.swml.xtext.validation

import at.fh.hagenberg.swml.xtext.language.LanguagePackage
import org.eclipse.xtext.validation.Check
import at.fh.hagenberg.swml.xtext.language.Entity

/**
 * This class contains custom validation rules. 
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class LanguageValidator extends AbstractLanguageValidator {

	public static val INVALID_NAME = 'invalidName'

	/**
	 * Validates the Entity name for starting with an capital letter.
	 */
	@Check
	def validateEntityNameStartsWithCapital(Entity entity) {
		if (!Character.isUpperCase(entity.name.charAt(0))) {
			warning('Name should start with a capital', LanguagePackage.Literals.ENTITY__NAME, INVALID_NAME)
		}
	}
}
