/**
 * generated by Xtext 2.10.0
 */
package at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Localized Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.LocalizedValue#getLocale <em>Locale</em>}</li>
 *   <li>{@link at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.LocalizedValue#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.ProjectGeneratorPackage#getLocalizedValue()
 * @model
 * @generated
 */
public interface LocalizedValue extends EObject
{
  /**
   * Returns the value of the '<em><b>Locale</b></em>' attribute.
   * The literals are from the enumeration {@link at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.Locale}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Locale</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Locale</em>' attribute.
   * @see at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.Locale
   * @see #setLocale(Locale)
   * @see at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.ProjectGeneratorPackage#getLocalizedValue_Locale()
   * @model
   * @generated
   */
  Locale getLocale();

  /**
   * Sets the value of the '{@link at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.LocalizedValue#getLocale <em>Locale</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Locale</em>' attribute.
   * @see at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.Locale
   * @see #getLocale()
   * @generated
   */
  void setLocale(Locale value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.ProjectGeneratorPackage#getLocalizedValue_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.LocalizedValue#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // LocalizedValue
