/**
 * generated by Xtext 2.10.0
 */
package at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Module</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.Module#getName <em>Name</em>}</li>
 *   <li>{@link at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.Module#getKey <em>Key</em>}</li>
 *   <li>{@link at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.Module#getCdiEnabled <em>Cdi Enabled</em>}</li>
 *   <li>{@link at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.Module#getMessageBundles <em>Message Bundles</em>}</li>
 *   <li>{@link at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.Module#getObservers <em>Observers</em>}</li>
 *   <li>{@link at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.Module#getJpaConfig <em>Jpa Config</em>}</li>
 *   <li>{@link at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.Module#getServiceConfig <em>Service Config</em>}</li>
 * </ul>
 *
 * @see at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.ProjectGeneratorPackage#getModule()
 * @model
 * @generated
 */
public interface Module extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.ProjectGeneratorPackage#getModule_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.Module#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Key</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Key</em>' attribute.
   * @see #setKey(String)
   * @see at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.ProjectGeneratorPackage#getModule_Key()
   * @model
   * @generated
   */
  String getKey();

  /**
   * Sets the value of the '{@link at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.Module#getKey <em>Key</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Key</em>' attribute.
   * @see #getKey()
   * @generated
   */
  void setKey(String value);

  /**
   * Returns the value of the '<em><b>Cdi Enabled</b></em>' attribute.
   * The literals are from the enumeration {@link at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.Boolean}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cdi Enabled</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cdi Enabled</em>' attribute.
   * @see at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.Boolean
   * @see #setCdiEnabled(at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.Boolean)
   * @see at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.ProjectGeneratorPackage#getModule_CdiEnabled()
   * @model
   * @generated
   */
  at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.Boolean getCdiEnabled();

  /**
   * Sets the value of the '{@link at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.Module#getCdiEnabled <em>Cdi Enabled</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cdi Enabled</em>' attribute.
   * @see at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.Boolean
   * @see #getCdiEnabled()
   * @generated
   */
  void setCdiEnabled(at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.Boolean value);

  /**
   * Returns the value of the '<em><b>Message Bundles</b></em>' containment reference list.
   * The list contents are of type {@link at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.Localized}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Message Bundles</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Message Bundles</em>' containment reference list.
   * @see at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.ProjectGeneratorPackage#getModule_MessageBundles()
   * @model containment="true"
   * @generated
   */
  EList<Localized> getMessageBundles();

  /**
   * Returns the value of the '<em><b>Observers</b></em>' containment reference list.
   * The list contents are of type {@link at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.Observer}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Observers</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Observers</em>' containment reference list.
   * @see at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.ProjectGeneratorPackage#getModule_Observers()
   * @model containment="true"
   * @generated
   */
  EList<Observer> getObservers();

  /**
   * Returns the value of the '<em><b>Jpa Config</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Jpa Config</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Jpa Config</em>' containment reference.
   * @see #setJpaConfig(JpaConfig)
   * @see at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.ProjectGeneratorPackage#getModule_JpaConfig()
   * @model containment="true"
   * @generated
   */
  JpaConfig getJpaConfig();

  /**
   * Sets the value of the '{@link at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.Module#getJpaConfig <em>Jpa Config</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Jpa Config</em>' containment reference.
   * @see #getJpaConfig()
   * @generated
   */
  void setJpaConfig(JpaConfig value);

  /**
   * Returns the value of the '<em><b>Service Config</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Service Config</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Service Config</em>' containment reference.
   * @see #setServiceConfig(ServiceConfig)
   * @see at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.ProjectGeneratorPackage#getModule_ServiceConfig()
   * @model containment="true"
   * @generated
   */
  ServiceConfig getServiceConfig();

  /**
   * Sets the value of the '{@link at.ooe.fh.mdm.herzog.dsl.proj.projectGenerator.Module#getServiceConfig <em>Service Config</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Service Config</em>' containment reference.
   * @see #getServiceConfig()
   * @generated
   */
  void setServiceConfig(ServiceConfig value);

} // Module
